const MESSAGES_API = "http://localhost:8080/api/messages";
const USERS_API = "http://localhost:8080/api/users"
export const FIND_MOST_RECENT_MESSAGE = MESSAGES_API + "/findMostRecentPrivateMessageForUser";
export const FIND_ALL_MESSAGES_FOR_USERS = MESSAGES_API + "/findAllMessagesForUsers";
export const MARK_ALL_RECEIVED_MESSAGES_AS_SEEN = MESSAGES_API + "/markAllReceivedMessagesAsSeen";
export const IMAGE_MESSAGE_UPLOAD = MESSAGES_API + "/imageMessageUpload";
export const VOCAL_MESSAGE_UPLOAD = MESSAGES_API + "/vocalMessageUpload";
export const GET_ALL_USER_PROFILES = USERS_API + "/getAllUserProfiles";
export const DUMMY_AUTH = USERS_API + "/dummyAuth";
export const GET_USER_PROFILE = MESSAGES_API + "/getUserProfileId";
